language: node_js
node_js:
  - '14.16.0'

before_install:
  - npm install -g @angular/cli
install: npm install

branches:
  only:
    - master


deploy:
  provider: heroku
  app: social-network-app1
  skip_cleanup: true
  api_key: "fk03xhnmZgVvyoD7Glgf0/AXwGUATimFeL0w7gR4Cy5iDjB7btLKKtmBe4hXVli9uPS8d1vCFX+5z7bJzR8CHcDI3dVzzbJdmqFULvlTU3i27dBFbJ36FOC8v/FHfkwSCmJaeZRbjy9cUru0xRjVhRCYtA3+cRRmKFc7VcucPIum51gaXBj9aR80yDKiBmzw99M6HyrqWI7vLsV4yId7n2IPqniRE1SHK2oR6I1Wq2c+XpQLu8WTOiwyaM2CEE+qDuFL1rUeJUHxeMTYH2NsqCDCkxfT3xK8uBYPVuYoE2VDI1VEKkQQ9jLoNMWnDKnVX2qPbnOsxPGB1RFGECMJkgSnw3oJIgE66gaMIQNFfh5QF+dcFbmDHjQBholjeGZHv8Hd7S2a+1KBeA3/2k4xOIHi/y8TSMKHn/9JiuqFI0UhuiVRAmWrcwJWt8ZUvMmLhyA8Bgd43IF8edGNLMHHaZQ8mFPBQTNVA+T/A99nJDRAj2patFZU31DuJRpMKQxa9xXuyET+Tlw4D2yV8CBMANSjTqq2BEe+uz3QCIKfEQ4WsiE/EdotpTj4WRNk2+sOoypUplBSk2bQ6VzitFMa5+l2LKCpfIIZXzU6W3C+TzqKEUTJbkxYQoC1GgfUGrPcU5DIdgnzb3op4HRf/Mbry5r8wCL/gh8KqVXbWehF4vw="
