language: node_js
node_js:
  - '14.16.0'

before_install:
  - npm install -g @angular/cli
install: npm install

branches:
  only:
    - master


deploy:
  provider: heroku
  app: social-network-app1
  skip_cleanup: true
  api_key:
    secure: "dujqBqXx4XjjnXgTuZ5UaJ/Ffu2leeRXFc6q/MM1BJlf1Z/8pxIgHr2TyEcuiysblVd+27KtCbZk3BrYvkWZgUVF8LqCbQO5u9/j3OH2ekwF0fuGdDbSwEq9B86WuEQh7uY0BX9cTBmTkagayblu4Cy3r9JHl4cidPI/6CjODMgGeLAO8Il8POfTmwp3SY+jQKgkJiffheIEl+Xf84QEPoq5guIF8xW1rb4LlRdAgL+NyMJaETlVOmaU0XAK60MWFP+AAnImE3o0q6uK+YiO729NIsywbSsR9I2zu06A9gINqUs9Er7Bw/qvjqC7oaVQw8EjX+9qkJS4wXsgGeyfn6UieuYWwnBXoEFapN5xaAai/RXWDT+dip3JcfuZn6JPfmAeAYSFGLNpj8Na52M26nji0ax7EjWV+D0VKCayF1z8Mzh6iHbTPh2a2zj4iwEjg2gfYFV6P0VkEbeOLLQQEXDaUqiE9F1Ae8d1vHpfcDUCuFsvvDTwRFfU17WBhtffVklCKkZJHAcLV+pbdQFLp0Bu3a/idEttX7DNjHnQrNX3mHlmCNkFmFsD1LAdPBZr9f0xQIMXB2bs7PtYWBl1CIrlBj87SavH+bYoY1TrUAdNuorkcY9z5zCKGE7DaFzgWlOlnOYHatNP3OL2x4i5aABuutFP31s8oFuBYnyQd+g="
